name = "CGN-Simulated"
author = "Svemat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07940ceccefb986b54303bafd4ee1821d327d9c3aefcfe3b54a7a4fe413dd6d9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
