name = "CGN-Simulated"
author = "Svemat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4d0667cf165c66fee3ffb5d9ce2944ad35b5da290dca1d63e2a379bebd026e1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
