name = "CGN-Simulated"
author = "Svemat"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e475098920c996e917ca9fb2780e2fec37354ba272f1702ee9a46c6b2b21de81"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
